import type codeBlock from '~/components/_Index/codeBlock';
export type TypeWriter = {
  displayIndex: number;
  displayCodeOrder: (keyof typeof codeBlock)[];
  displayCode: (typeof codeBlock)[keyof typeof codeBlock];
  codeOutputIndex: number;
  blankCharArr: number[];
  revealedCharArr: number[];
  currentChar: number;
  currentRow: number;
  rollbackTo: number;
  totalChar: number;
  instance: any;
  appearStart: number;
  disappearStart: number;
  timeAfterLastChar: number;
  timeAfterAnimationFinished: number;
  previousTimeStamp: number;
  smallestIntervalBetweenCharAppear: number;
  largestIntervalBetweenCharAppear: number;
  smallestIntervalBetweenCharDisappear: number;
  largestIntervalBetweenCharDisappear: number;
  appearDurationUntilFullSpeed: number;
  disppearDurationUntilFullSpeed: number;
  disappearDelay: number;
  appearDelay: number;
  initialDelay: number;
};
