import { type ExtendType } from "../extend";

export default {
  colors: {
    "primary-dark-gray": "#1f2937",
    "background-light-gray": "#f7f7f7",
    "code-editor-one-dark-pro": "#282c34",
    "highlight-dark": "#2f3e52",
    "disabled-dark": "#141a23",
    yellow: "#fcd34d",
    "middle-yellow": "#FDE594",
    "pale-yellow": "#faf6e9",
    "light-yellow": "#fef6db",
    "bright-yellow": "#ffff43",
    "dark-yellow": "#e5ddc5",
    mint: "#6fdcbf",
    "middle-mint": "#A9EAD9",
    "light-mint": "#e2f8f2",
    "mint-up": "#a5d4bb",
    "mint-down": "#55af96",
    lilac: "#ae8fdb",
    "middle-lilac": "#CFBCEA",
    "light-lilac": "#efe9f8",
    "deep-sea": "#34afc5",
    sea: "#72cada",
    "middle-sea": "#ABDFE9",
    "light-sea": "#e3f4f8",
    "lilac-up": "#b1b1d8",
    sherbet: "#fef8b4",
    "mddle-sherbet": "#FFFACB",
    "light-sherbet": "#fffce1",
    pink: "#f7b8c2",
    "middle-pink": "#F7B8C2",
    "light-pink": "#fdf1f3",
    rose: "#dc849b",
    "middle-rose": "#EAB5C3",
    "light-rose": "#f8e6eb",
    marshmellow: "#d695b6",
    peach: "#f2c3c0",
    biscuit: "#ad998a",
    oat: "#cbc1bd",
    mid: "#cccccc",
    dark: "#404040",
    "dark-down": "#303145",
    tomato: "#ff6347",
    "middle-tomato": "#FFA291",
    "light-tomato": "#ffe0da",
  },
} satisfies { colors: NonNullable<ExtendType["colors"]> };
