import { type ExtendType } from "../extend";

export default {
  colors: {
    "primary-dark-gray": "#1f2937",
    "background-light-gray": "#f7f7f7",
    "code-editor-one-dark-pro": "#282c34",
    yellow: "#fcd34d",
    "light-yellow": "#fef6db",
    "bright-yellow": "#ffff43",
    mint: "#6fdcbf",
    "light-mint": "#e2f8f2",
    "mint-up": "#a5d4bb",
    "mint-down": "#55af96",
    lilac: "#ae8fdb",
    "light-lilac": "#efe9f8",
    sea: "#72cada",
    "light-sea": "#e3f4f8",
    "lilac-up": "#b1b1d8",
    sherbet: "#fef8b4",
    "light-sherbet": "#fffce1",
    pink: "#f7b8c2",
    "light-pink": "#fdf1f3",
    rose: "#dc849b",
    marshmellow: "#d695b6",
    peach: "#f2c3c0",
    biscuit: "#ad998a",
    oat: "#cbc1bd",
    mid: "#cccccc",
    dark: "#404040",
    "dark-down": "#303145",
    tomato: "#ff6347",
  },
} satisfies { colors: NonNullable<ExtendType["colors"]> };
